# Generated by Django 3.2.12 on 2022-07-27 21:44

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'compañía', 'verbose_name_plural': 'compañías'},
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={'ordering': ['name'], 'verbose_name': 'género', 'verbose_name_plural': 'géneros'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-created'], 'verbose_name': 'película', 'verbose_name_plural': 'películas'},
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Compañía'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvapp.company', verbose_name='Compañia'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Resumen'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genders',
            field=models.ManyToManyField(to='mvapp.Gender', verbose_name='Géneros'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='movies', verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Película'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='premiere',
            field=models.SmallIntegerField(verbose_name='Año de Estreno'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Muy mala'), (2, 'Mala'), (3, 'Mediocre'), (4, 'Buena'), (5, 'Excelente')], verbose_name='Rating'),
        ),
    ]
