# Generated by Django 4.2.3 on 2023-07-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mvapp", "0002_auto_20220727_1844"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="rating",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Vey bad"),
                    (2, "Bad"),
                    (3, "Mediocre"),
                    (4, "Good"),
                    (5, "Excellent"),
                ],
                verbose_name="Rating",
            ),
        ),
    ]
